name: ci

on:
  pull_request:

jobs:
  lint-bash-scripts:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Lint Bash scripts
        uses: docker://koalaman/shellcheck-alpine:v0.7.0
        with:
          args: .github/lint-scripts.sh

  lint-docker-files:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1    
      - name: lint zammad dockerfile
        uses: brpaz/hadolint-action@master
        with:
          dockerfile: containers/zammad/Dockerfile
      - name: lint elasticsearch dockerfile
        uses: brpaz/hadolint-action@master
        with:
          dockerfile: containers/zammad-elasticsearch/Dockerfile
      - name: lint postgresql dockerfile
        uses: brpaz/hadolint-action@master
        with:
          dockerfile: containers/zammad-postgresql/Dockerfile                 

  test-docker-compose:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: pull container images
        run: docker-compose pull
      - name: run docker-compose up
        run: docker-compose up --detach
      - name: add autowizard file
        run: docker cp .github/auto_wizard.json zammad-docker-compose_zammad-railsserver_1:/opt/zammad
      - name: run tests
        run: .github/tests.sh
